name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install needed tools
        run: |
          brew install ldid dpkg
          
      - name: Select Xcode version (14.0)
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.0.app
          
      - name: Build & Sign Application
        run: |
          make
          
      - name: Upload TrollStore .tipa
        uses: actions/upload-artifact@v3.1.0
        with:
          name: AntoineTrollstore.tipa
          path: ${{ github.workspace }}/build/AntoineTrollstore.tipa
          
      - name: Upload deb for Jailbroken devices
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Antoine
          path: ${{ github.workspace }}/build/Antoine.deb
